/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:cc40d90f-4c7e-49e5-8761-36bb274950c9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_YskgLoDAN",
    "aws_user_pools_web_client_id": "37o12k85v0m7h1n4oiipl7t3k6",
    "oauth": {}
};


export default awsmobile;
